services:
  - type: web
    name: chatbox-backend
    env: python
    rootDir: backend
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /health 