services:
  - type: web
    name: chatbox-backend
    env: python
    rootDir: backend
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r ../requirements.txt
      cp ../requirements.txt .
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production 